<?php
$title = 'Reports Center';
require_once __DIR__ . '/../../middleware/Auth.php';
include __DIR__ . '/../layouts/corporate_header.php';

$auth = Auth::getInstance();
try {
    $pdo = getDBConnection();
    $reports = $pdo->query("SELECT r.*, u.username FROM reports r LEFT JOIN users u ON r.generated_by = u.id ORDER BY r.created_at DESC")->fetchAll();
} catch (PDOException $e) { $reports = []; }
?>

<div class="panel">
    <div class="panel-header panel-header-between">
        <h3>Reports Center</h3>
        <button class="btn btn-primary btn-sm" onclick="alert('Report generation initiated via API')">+ Generate Report</button>
    </div>
    <div class="panel-body">
        <?php if (empty($reports)): ?>
            <div class="empty-state"><div class="empty-icon">&#128202;</div><h3>No Reports Generated</h3><p>Generate reports from the corporate dashboard.</p></div>
        <?php else: ?>
        <div class="table-responsive"><table class="table"><thead><tr><th>Report Name</th><th>Type</th><th>Format</th><th>Generated By</th><th>Date</th><th>Actions</th></tr></thead>
            <tbody><?php foreach ($reports as $r): ?><tr><td><strong><?= htmlspecialchars($r['report_name']) ?></strong></td><td><?= $r['report_type'] ?></td><td><span class="badge"><?= $r['report_format'] ?></span></td><td><?= htmlspecialchars($r['username'] ?? '-') ?></td><td><?= date('M j, Y', strtotime($r['created_at'])) ?></td><td><a href="#" class="btn btn-ghost btn-sm">Download</a></td></tr><?php endforeach; ?></tbody></table></div>
        <?php endif; ?>
    </div>
</div>
<?php include __DIR__ . '/../layouts/corporate_footer.php'; ?>
